export const areaAtuacaoList = [
  { area: 'Administração' },
  { area: 'Recursos Humanos' },
  { area: 'Finanças e Contabilidade' },
  { area: 'Marketing' },
  { area: 'Tecnologia da Informação' },
  { area: 'Segurança Cibernética' },
  { area: 'Pesquisa e Desenvolvimento' },
  { area: 'Operações e Logística' },
  { area: 'Help Desk' },
  { area: 'Jurídico' },
  { area: 'Comunicação' },
  { area: 'Manufatura' },
  { area: 'Qualidade e Controle de qualidade' },
  { area: 'Saúde e Segurança no trabalho' },
  { area: 'Sustentabilidade e Responsabilidade social' },
  { area: 'Ciência de Dados' },
  { area: 'Suporte à infraestrutura' },
  { area: 'Facilities' },
]
