export const competenciasLinguagens = [
  { lingua: "Português" },
  { lingua: "Inglês" },
  { lingua: "Espanhol" },
  { lingua: "Chinês (Mandarim)" },
  { lingua: "Hindi" },
  { lingua: "Árabe" },
  { lingua: "Bengali" },
  { lingua: "Russo" },
  { lingua: "Japonês" },
  { lingua: "Alemão" },
  { lingua: "Francês" },
  { lingua: "Coreano" },
  { lingua: "Italiano" },
  { lingua: "Holandês" },
  { lingua: "Turco" },
  { lingua: "Hebraico" },
  { lingua: "Sueco" },
  { lingua: "Polonês" },
  { lingua: "Grego" },
  { lingua: "Tailandês" },
  { lingua: "Vietnamita" },
  { lingua: "Filipino (Tagalo)" },
  { lingua: "Persa (Farsi)" },
  { lingua: "Cantonês" },
  { lingua: "Dinamarquês" },
  { lingua: "Finlandês" },
  { lingua: "Norueguês" },
  { lingua: "Húngaro" },
  { lingua: "Tâmil" },
  { lingua: "Checo" },
];
