export const competenciasSociaisList = [
  { competenciaSocial: 'Comunicação eficaz' },
  { competenciaSocial: 'Colaboração' },
  { competenciaSocial: 'Empatia' },
  { competenciaSocial: 'Resolução de Conflitos' },
  { competenciaSocial: 'Habilidade de Negociação' },
  { competenciaSocial: 'Trabalho em equipe' },
  { competenciaSocial: 'Liderança' },
  { competenciaSocial: 'Adaptabilidade' },
  { competenciaSocial: 'Habilidade de Escuta Ativa' },
  { competenciaSocial: 'Compreensão Cultural' },
  { competenciaSocial: 'Comunicação não verbal' },
  { competenciaSocial: 'Trabalho sob pressão' },
  { competenciaSocial: 'Gerenciamento de Tempo' },
  { competenciaSocial: 'Gerenciamento de Estresse' },
  { competenciaSocial: 'Habilidade de Delegação' },
  { competenciaSocial: 'Respeito à Hierarquia' },
  { competenciaSocial: 'Pensamento Criativo' },
  { competenciaSocial: 'Integridade e Ética Profissional' },
  { competenciaSocial: 'Comunicação Digital' },
  { competenciaSocial: 'Compreensão das Redes Sociais' },
  { competenciaSocial: 'Comunicação Clara e Concisa' },
  { competenciaSocial: 'Capacidade de Influenciar' },
  { competenciaSocial: 'Gestão de Relacionamentos' },
  { competenciaSocial: 'Inteligência Emocional' },
  { competenciaSocial: 'Respeito à Diversidade' },
  { competenciaSocial: 'Pensamento Crítico' },
  { competenciaSocial: 'Resolução de Problemas em Grupo' },
  { competenciaSocial: 'Construção de Confiança' },
  { competenciaSocial: 'Feedback Construtivo' },
  { competenciaSocial: 'Gerenciamento de Conflitos' },
  { competenciaSocial: 'Empatia Cultural' },
  { competenciaSocial: 'Habilidade de Apresentação' },
  { competenciaSocial: 'Gestão da Mudança' },
  { competenciaSocial: 'Resolução de Problemas de Cliente' },
  { competenciaSocial: 'Inovação Colaborativa' },
  { competenciaSocial: 'Gestão de Projetos' },
  { competenciaSocial: 'Habilidade de Influência Online' },
  { competenciaSocial: 'Criatividade em Equipe' },
  { competenciaSocial: 'Mentoria' },
  { competenciaSocial: 'Construção de Alianças Estratégicas' },
];
